name: first workflow
on: 
  workflow_dispatch:
    inputs:
      debug:
        type: string

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "helloss"
  my-second-job:
    env: 
      firstvar: "parag"
    runs-on: macos-latest
    steps:
      - run: echo "by worlds"
      - run: echo "${{ inputs.debug }}"
      - run: echo "${{ vars.debugg }}"

  build:
    runs-on: ubuntu-latest
    steps:
          - name: Define Workflow Variable
            id: set_var
            run: |
              echo "Setting Workflow Variable"
              echo "name=Max" >> "$GITHUB_OUTPUT"
          - name: Use Workflow Variable
            run: |
              echo "Workflow Variable Value: ${{ steps.set_var.outputs.name }}"
    
    